### ISSUE TITLE
package-lock and yarn-lock found.

### ISSUE THREAD

**Issue by MichaelDimmitt** [mattblackdev/tiny-empire#1]
Pick a side!!

**Comment by MichaelDimmitt** [comment]
npm install works, yarn install ... gives a styled component error.

**Comment by MichaelDimmitt** [comment]
@mattblackdev

**Comment by MichaelDimmitt** [comment]
# When using Yarn
![Screen Shot 2019-11-16 at 12 25 26 PM](https://user-images.githubusercontent.com/11463275/68996745-3a8c8800-086c-11ea-8f45-2b70aace9fc9.png)

**Comment by mattblackdev** [comment]
@MichaelDimmitt hey dude I started this a long time ago and it fell off my radar. I have a ton of local changes. If you’re interested in the project I can clean it up a bit and push?

**Comment by MichaelDimmitt** [comment]
It is semi interesting, a 2d game with characters fighting to the death.

**Comment by MichaelDimmitt** [comment]
I was trying out some of your projects. I would push the updates or archive the project, either/or.

Though, it is fun to see how some of these games work. 🎉

**Comment by mattblackdev** [comment]
Nice! Yeah locally it is 3D using react-three-fiber

**Comment by mattblackdev** [comment]
@MichaelDimmitt okay I updated the repo. It's totally different, as you'll see. Btw, I always use yarn these days lol.
